##############################################
#               Ultra Chat                   #
##############################################
#Color GUI Settings:
#If true the command will be /chat color instead of /color
ChatColor_Command: false

#Used for assistance in development. Read more about it here:
# https://bstats.org/getting-started
bstats: true
#Restrict plugins from changing things in the config.
apirestrict: false
#Some of the chat formats break the mute function in plugins.
#This plugin hooks into ban/mute plugins and allow it to work.
#If set to true then the plugin will hook into that plugin.
#Suggest more ban plugins here: https://github.com/ryandw11/UltraChat/issues !
#Or ask the ban plugin author.
pluginhooks:
    Essentials: true
    AdvancedBan: true


#############################################
#               Anti - Swear                #
#############################################

Anti_Swear_Enabled: false

Blocked_Words:
    - fuck
    - fu
    - shit
    - f*ck
    - crap
    - ass
    - jackass
    - sh*t
    - asshole
    - fucker

#############################################
#              Join Settings                #
#############################################
#New player join. If the player hasn't joined the server before then this message will play. If you don't want it put none.
New_Player: '&d%player% has just joined the server for the first time! Welcome!'

#Moto of the day. You can use chat colors.
#If you have PlaceholderAPI installed you can use these placeholders: https://www.spigotmc.org/wiki/placeholderapi-placeholders/!
Motd_Enabled: true
Motd:
    - '&6Welcome to the server,&r %player_name%&6.'
    - '&6There are currently&b %server_online% &6players online!'
    
Join_Message: '&e%player% has joined the server!'
Leave_Message: '&e%player% has left the server!'
#############################################
#              JSON Component               #
#############################################
# This is a system to create JSON pockets with in a message.
# It uses a placerholder system to use.
#The name of the component:
JSON_Components:
    normal_chat:
    #The base message of the component
        Message: '%prefix% %player% %suffix%'
        #The component events
        Events:
        #A click event {Optional}
            Click:
            # One and only one of the Click Operations. Full list includes: {Open_URL, Run_Command, Suggest_Command}
                Suggest_Command: '/msg %player%'
            # When the player hovers over the base text.
            Hover:
                Show_Text:
                - '&bLine One'
                - '&3Line Two'
##############################################
#                                            #
#                  Chat                      #
#                                            #
##############################################
# Vailed types: normal, channel, and range.
# Set to nothing to not format the chat.
# Check the wiki for an explenation of each type!
chat_format: 'normal'

#The default color that opped players chat in. Do &r for none.
Op_Chat_Color: '&c'

#Console Chat Log: (JSON chat only!)
#With json on the chat no longer prints to the console. This option fixes that issue! Set to true if you want it enabled!
console_log: false

#Variables: %prefix% - Gives you the players prefix. %suffix% - gives you the player suffix!
#You can use PlaceHolderAPI here! Check out the placeholders here: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
#You can have unlimited custom chat formats.
#Note: If PlaceHolderAPI placeholders are not showing up please check to make sure you have the extension installed and that you reloaded the plugin. 
#Notice: The JSON is only if the JSON above is set to true. JSON can also use PlaceHolderAPI!
########################
#   Important Note!    #
########################
# If you give a player the '*' permission they will have every single custom chat. 
# When json is enabled the message is sent several times based on the number of custom formats you have!
# To avoid this give them the permission -(yourpermission). Ex: -ultrachat.chat.1
Custom_Chat:
    permission_format:
        'ultrachat.chat.example': '{normal_chat} &7>>'
    #For any player oped.
    Op_Chat: '{normal_chat} &c>> '
    #The default chat when a player does not have a custom one.
    Default_Chat: '{normal_chat} &7>>'

##############################################
#                Channels                    #
##############################################
#Note: Custom Chat must be enabled for this to work!
#Edit the channels.yml when the server is stopped!
#Default Channel. This is the channel the player first joins the server. It is also given when the channel the player is on does not exsist.
Default_Channel: 'global'
#This is a list for the channels. It will only affect the list of channels. (Name should match the same as the one in the channels.yml)
Channel_List:
- global
- vip

##############################################
#                   Range                    #
##############################################
#The global channel which everyone can see.
#All of these formats support Components. See Normal Chat for an example.
Global:
    format: '&6[Global]&r %prefix% %player% %suffix% &7>>'
World:
    format: '&d[World]&r %prefix% %player% %suffix% &7>>'
Local:
    format: '&b[Local]&r %prefix% %player% %suffix% &7>>'
    range: 100